openapi: 3.0.0
info:
  version: 1.0.0
  title: Insolar Block Explorer API
  contact:
    name: Insolar dev team
    url: 'https://insolar.io/team.html'
    email: dev-support@insolar.io
  description: |
    BE description
servers:
  - url: example.com
    description: The test server
tags:
  - name: pulse
  - name: jetdrop
  - name: record
paths:
  /api/v1/pulses:
    get:
      summary: Pulses
      operationId: pulses
      tags:
        - pulse
      parameters:
        - $ref: '#/components/parameters/PulsesQueryParameterLimit'
        - $ref: '#/components/parameters/PulsesQueryParameterOffset'
        - $ref: '#/components/parameters/PulsesQueryParameterFrom_item'
        - $ref: '#/components/parameters/PulsesQueryParameterFrom_pulse_number'
        - $ref: '#/components/parameters/PulsesQueryParameterTo_pulse_number'
        - $ref: '#/components/parameters/PulsesQueryParameterFrom_jetdrop_amount'
        - $ref: '#/components/parameters/PulsesQueryParameterTo_jetdrop_amount'
      responses:
        '200':
          description: Internal server error
          content:
            application/json:
              schema:
                properties:
                  total:
                    type: integer
                    format: int64
                    description: total resuls
                    example: 100
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        pulse_number:
                          type: integer
                          format: int64
                          description: pulse number
                          example: 43648102
                        prev_pulse_number:
                          type: integer
                          format: int64
                          description: previous pulse number
                          example: 43648092
                        next_pulse_number:
                          type: integer
                          format: int64
                          description: next pulse number
                          example: 43648112
                        jetdrop_amount:
                          type: integer
                          format: int64
                          description: amount of all jetdrop in the pulse
                          example: 16
                        record_amount:
                          type: integer
                          format: int64
                          description: number of all records in the pulse
                          example: 245
                        timestamp:
                          type: integer
                          format: int64
                          description: unix timestamp
                          example: 1451743413
                        is_complete:
                          type: bool
                          description: does pulse complite fully?
                          example: true
                      title: PulseResponse200
                title: PulsesResponse200
  '/api/v1/pulses/{pulse-number}':
    get:
      summary: Pulse
      operationId: pulse
      tags:
        - pulse
      parameters:
        - in: path
          name: pulse-number
          required: true
          schema:
            type: integer
            minimum: 0
            default: 20
          description: The Pulse number.
      responses:
        '200':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  pulse_number:
                    type: integer
                    format: int64
                    description: pulse number
                    example: 43648102
                  prev_pulse_number:
                    type: integer
                    format: int64
                    description: previous pulse number
                    example: 43648092
                  next_pulse_number:
                    type: integer
                    format: int64
                    description: next pulse number
                    example: 43648112
                  jetdrop_amount:
                    type: integer
                    format: int64
                    description: amount of all jetdrop in the pulse
                    example: 16
                  record_amount:
                    type: integer
                    format: int64
                    description: number of all records in the pulse
                    example: 245
                  timestamp:
                    type: integer
                    format: int64
                    description: unix timestamp
                    example: 1451743413
                  is_complete:
                    type: bool
                    description: does pulse complite fully?
                    example: true
                title: PulseResponse200
  '/api/v1/jetdrops/{jetdrop-id}':
    get:
      summary: JetDrop by ID
      operationId: jetdropByID
      tags:
        - jetdrop
      parameters:
        - name: jetdrop-id
          in: path
          required: true
          schema:
            type: string
          description: The ID of JetDrop.
      responses:
        '200':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  jetdrop_id:
                    type: string
                    description: JetDrop ID is concantination of jet_id and pulse_number
                    example: '43648102:0010'
                  next_jetdrop_id:
                    type: array
                    format: string
                    description: Next jetdrop_id
                    example:
                      - '43648104:00100'
                      - '43648104:00101'
                    items:
                      type: string
                      description: jetDrop ID is concantination of jet_id and pulse_number
                      example: '43648102:0010'
                  prev_jetdrop_id:
                    type: array
                    format: string
                    description: Previous jetdrop_id
                    example:
                      - '43648101:0010'
                    items:
                      type: string
                      description: jetDrop ID is concantination of jet_id and pulse_number
                      example: '43648102:0010'
                  jet_id:
                    type: string
                    description: Jet ID
                    example: '0010'
                  pulse_number:
                    type: integer
                    format: int64
                    description: Pulse number
                    example: 43612021
                  record_amount:
                    type: integer
                    format: int64
                    description: Number of all records in the pulse
                    example: 245
                  timestamp:
                    type: integer
                    format: int64
                    description: Unix timestamp
                    example: 1451743413
                  hash:
                    type: string
                    description: Record hash
                    example: >-
                      0JfQtNC10YHRjCDQvNC+0LPQu9CwINCx0YvRgtGMINCy0LDRiNCwINGA0LXQutC70LDQvNCw
                title: JetDrop by IDResponse200
  '/api/v1/jetdrops/{jetdrop-id}/records':
    get:
      summary: JetDrop records
      operationId: jetdrop_records
      tags:
        - record
      parameters:
        - $ref: '#/components/parameters/JetDropRecordsQueryParameterLimit'
        - $ref: '#/components/parameters/JetDropRecordsQueryParameterOffset'
        - $ref: '#/components/parameters/JetDropRecordsQueryParameterFrom_item'
        - $ref: '#/components/parameters/JetDropRecordsQueryParameterType'
        - name: jetdrop-id
          in: path
          required: true
          schema:
            type: string
          description: The ID of JetDrop.
      responses:
        '200':
          description: Internal server error
          content:
            application/json:
              schema:
                properties:
                  total:
                    type: integer
                    format: int32
                    description: total resuls
                    example: 100
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        reference:
                          type: string
                          description: record reference
                          example: >-
                            insolar:1Apn2LmIL4ehiZ5NN0fLo5qJR7CeodnLDUtmvI9TrWVw.record
                        object_reference:
                          type: string
                          description: object reference
                          example: 'insolar:1AAEAAS2JLnvh2bkLUUlUijqcp7--k8_GIz9qLKxZXLE'
                        prototype_reference:
                          type: string
                          description: prototype reference
                          example: 'insolar:1Ajx0cKvLPzFwV-vW4jp-wuuwUcDv1lgvQFrIAvQYH3g'
                        type:
                          type: string
                          description: record type
                          enum:
                            - state
                            - request
                            - result
                          example: state
                        timestamp:
                          type: integer
                          format: int64
                          description: unix timestamp
                          example: 1451743413
                        payload:
                          type: string
                          description: record payload
                          example: >-
                            0KLQvtC/INC60L7QvdGC0LXQvdGCLCDQu9GD0YfRiNCw0Y8g0L/Qu9Cw0YLRhNC+0YDQvNCw
                        hash:
                          type: string
                          description: record hash
                          example: >-
                            0JfQtNC10YHRjCDQvNC+0LPQu9CwINCx0YvRgtGMINCy0LDRiNCwINGA0LXQutC70LDQvNCw
                        pulse_number:
                          type: integer
                          format: int64
                          description: pulse number
                          example: 43612021
                        jet_id:
                          type: string
                          description: jet ID
                          example: '0010'
                        jetdrop_id:
                          type: string
                          description: >-
                            jetDrop ID is concantination of jet_id and
                            pulse_number
                          example: '43648102:0010'
                title: JetDrop recordsResponse200
  '/api/v1/lifeline/{object-reference}/records':
    get:
      summary: Object Lifeline
      operationId: object_lifeline
      tags:
        - record
      parameters:
        - name: object_reference
          in: path
          required: true
          schema:
            type: string
          description: The reference of object.
        - $ref: '#/components/parameters/ObjectLifelineQueryParameterLimit'
        - $ref: '#/components/parameters/ObjectLifelineQueryParameterOffset'
        - $ref: '#/components/parameters/ObjectLifelineQueryParameterFrom_item'
        - $ref: '#/components/parameters/ObjectLifelineQueryParameterType'
      responses:
        '200':
          description: Internal server error
          content:
            application/json:
              schema:
                properties:
                  total:
                    type: integer
                    format: int64
                    description: total resuls
                    example: 100
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        reference:
                          type: string
                          description: record reference
                          example: >-
                            insolar:1Apn2LmIL4ehiZ5NN0fLo5qJR7CeodnLDUtmvI9TrWVw.record
                        object_reference:
                          type: string
                          description: object reference
                          example: 'insolar:1AAEAAS2JLnvh2bkLUUlUijqcp7--k8_GIz9qLKxZXLE'
                        prototype_reference:
                          type: string
                          description: prototype reference
                          example: 'insolar:1Ajx0cKvLPzFwV-vW4jp-wuuwUcDv1lgvQFrIAvQYH3g'
                        type:
                          type: string
                          description: record type
                          enum:
                            - state
                            - request
                            - result
                          example: state
                        timestamp:
                          type: integer
                          format: int64
                          description: unix timestamp
                          example: 1451743413
                        payload:
                          type: string
                          description: record payload
                          example: >-
                            0KLQvtC/INC60L7QvdGC0LXQvdGCLCDQu9GD0YfRiNCw0Y8g0L/Qu9Cw0YLRhNC+0YDQvNCw
                        hash:
                          type: string
                          description: record hash
                          example: >-
                            0JfQtNC10YHRjCDQvNC+0LPQu9CwINCx0YvRgtGMINCy0LDRiNCwINGA0LXQutC70LDQvNCw
                        pulse_number:
                          type: integer
                          format: int64
                          description: pulse number
                          example: 43612021
                        jet_id:
                          type: string
                          description: jet ID
                          example: '0010'
                        jetdrop_id:
                          type: string
                          description: >-
                            jetDrop ID is concantination of jet_id and
                            pulse_number
                          example: '43648102:0010'
                title: Object LifelineResponse200
components:
  parameters:
    PulsesQueryParameterLimit:
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
      description: The numbers of items to return.
    PulsesQueryParameterOffset:
      in: query
      name: offset
      required: false
      schema:
        type: integer
        minimum: 0
      description: The number of items to skip before starting to collect the result set.
    PulsesQueryParameterFrom_item:
      name: from_item
      in: query
      required: true
      schema:
        type: string
      description: The numbers of items to return.
    PulsesQueryParameterFrom_pulse_number:
      in: query
      name: from_pulse_number
      required: false
      schema:
        type: integer
        minimum: 0
        default: 0
      description: From which Pulse number.
    PulsesQueryParameterTo_pulse_number:
      in: query
      name: to_pulse_number
      required: false
      schema:
        type: integer
        minimum: 1
        default: 20
      description: To which Pulse number.
    PulsesQueryParameterFrom_jetdrop_amount:
      in: query
      name: from_jetdrop_amount
      required: false
      schema:
        type: integer
        minimum: 0
        default: 0
      description: To which jetdrop_amount.
    PulsesQueryParameterTo_jetdrop_amount:
      in: query
      name: to_jetdrop_amount
      required: false
      schema:
        type: integer
        minimum: 1
        default: 200
      description: From which jetdrop_amount.
    JetDropRecordsQueryParameterLimit:
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
      description: The numbers of items to return.
    JetDropRecordsQueryParameterOffset:
      in: query
      name: offset
      required: false
      schema:
        type: integer
        minimum: 0
      description: The number of items to skip before starting to collect the result set.
    JetDropRecordsQueryParameterFrom_item:
      name: from_item
      in: query
      required: true
      schema:
        type: string
      description: The numbers of items to return.
    JetDropRecordsQueryParameterType:
      name: type
      in: query
      description: The record type.
      required: false
      schema:
        type: string
        enum:
          - state
          - request
          - result
    ObjectLifelineQueryParameterLimit:
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
      description: The numbers of items to return.
    ObjectLifelineQueryParameterOffset:
      in: query
      name: offset
      required: false
      schema:
        type: integer
        minimum: 0
      description: The number of items to skip before starting to collect the result set.
    ObjectLifelineQueryParameterFrom_item:
      name: from_item
      in: query
      required: true
      schema:
        type: string
      description: The numbers of items to return.
    ObjectLifelineQueryParameterType:
      name: type
      in: query
      description: The record type.
      required: false
      schema:
        type: string
        enum:
          - state
          - request
          - result
