openapi: 3.0.0
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: 'http://petstore.swagger.io/v1'
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - $ref: '#/components/parameters/ListAllPetsQueryParameterLimit'
      responses:
        '200':
          description: unexpected error
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                items:
                  type: object
                  required:
                    - id
                    - name
                    - code
                    - message
                  properties:
                    id:
                      type: integer
                      format: int64
                    name:
                      type: string
                    tag:
                      type: string
                    code:
                      type: integer
                      format: int32
                    message:
                      type: string
                  title: Info for a specific petResponse200
                title: List all petsResponse200
                required:
                  - code
                  - message
                properties:
                  code:
                    type: integer
                    format: int32
                  message:
                    type: string
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      responses:
        '201':
          description: unexpected error
          content:
            application/json:
              schema:
                title: Create a petResponse201
                type: object
                required:
                  - code
                  - message
                properties:
                  code:
                    type: integer
                    format: int32
                  message:
                    type: string
  '/pets/{petId}':
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: unexpected error
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  - name
                  - code
                  - message
                properties:
                  id:
                    type: integer
                    format: int64
                  name:
                    type: string
                  tag:
                    type: string
                  code:
                    type: integer
                    format: int32
                  message:
                    type: string
                title: Info for a specific petResponse200
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
        - code
        - message
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
        code:
          type: integer
          format: int32
        message:
          type: string
      title: Info for a specific petResponse200
    Pets:
      type: object
      items:
        type: object
        required:
          - id
          - name
          - code
          - message
        properties:
          id:
            type: integer
            format: int64
          name:
            type: string
          tag:
            type: string
          code:
            type: integer
            format: int32
          message:
            type: string
        title: Info for a specific petResponse200
      title: List all petsResponse200
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  parameters:
    ListAllPetsQueryParameterLimit:
      name: limit
      in: query
      description: How many items to return at one time (max 100)
      required: false
      schema:
        type: integer
        format: int32
