openapi: "3.0.0"
info:
  version: 1.0.0
  title: Insolar Explorer API
  contact:
    name: Insolar dev team
    url: https://insolar.io/team.html
    email: dev-support@insolar.io
  # x-logo:
  #   url: https://insolar.io/logo.svg
  #   altText: Insolar
  #   href: https://insolar.io
  description: |
    # Insolar Explorer API documentation

    [Insolar Explorer](https://github.com/insolar/block-explorer) is a service that allows users to search for and view the contents of individual transactions, records, lifelines, jet drops and jets.

    Insolar Explorer provides a REST-like API interface.

    ## Basic entities

    * Record—minimum unit of storage that contains an associated request, response, and maintenance details
    * Lifeline—sequence of records for object state where an object is a smart contract instance
    * Jet drop—unit of storage for jets
    * Jet—groups of lifelines

    * Jet drop ID—combination of jet id with pulse number.
    * Index—combination of pulse number with order (record number in a jet drop).


    ## Filtering, pagination, sorting

    API provides filtering based on a range of values: greater than and less than, or greater than or equal to and less than or equal to.

    API provides a combination of offset and seek pagination.

    Pagination can be applied using:
    * Combination of a starting point (`from_*`), number of entries per page (`limit`) and number of entries to skip from the starting point (`offset`).
    * Just `limit` to get a limited array of the latest data.
    * Combination of the filtering parameters `*_gt`/`*_gte` and `*_lt`/`*_lte`, and `limit`.

    Some requests can be sorted in the descending (`*_desc`)  or ascending (`*_asc`) order.

servers:
  - url: example.com
    description: Test server.

tags:
  - name: Pulse
    description: Pulse is the trigger for the production of a new jet drop. Pulse also serves as the default time unit on Insolar Network.
  - name: Jet drop
    description: Jet drop is the unit of storage for jets. Jet drop contains all records that are registered within a pulse and associated with a particular jet.
  - name: Record
    description: Record is the minimum unit of storage that contains an associated request, response, and maintenance details. Records are grouped by lifeline.
  - name: Search
    description: Search provides detailed entity metadata.

paths:
  /api/v1/pulses:
    $ref: 'requests/pulses.yaml'
  /api/v1/pulses/{pulse_number}:
    $ref: 'requests/pulse.yaml'
  /api/v1/jet-drops/{jet_drop_id}:
    $ref: 'requests/jet-drop-byid.yaml'
  /api/v1/pulses/{pulse_number}/jet-drops:
    $ref: 'requests/jet-drops-bypulse.yaml'
  /api/v1/jets/{jet_id}/jet-drops:
    $ref: 'requests/jet-drops-byjetid.yaml'
  /api/v1/jet-drops/{jet_drop_id}/records:
    $ref: 'requests/records.yaml'
  /api/v1/lifeline/{object_reference}/records:
    $ref: 'requests/lifeline.yaml'
  /api/v1/search:
    $ref: 'requests/search.yaml'

