openapi: "3.0.0"
info:
  version: 1.0.0
  title: Insolar Block Explorer API
  contact:
    name: Insolar dev team
    url: https://insolar.io/team.html
    email: dev-support@insolar.io
  description: |
    BE description


servers:
  - url: example.com
    description: The test server.

tags:
  - name: pulse
  - name: jetdrop
  - name: record


paths:
  /api/v1/pulses:
    $ref: 'requests/pulses.yaml'
  /api/v1/pulses/{pulse_number}:
    $ref: 'requests/pulse.yaml'
  /api/v1/jetdrops/{jet_drop_id}:
    $ref: 'requests/jetdrop-byid.yaml'
  /api/v1/pulses/{pulse_number}/jetdrops:
    $ref: 'requests/jetdrops-bypulse.yaml'
  /api/v1/jets/{jet_id}/jetdrops:
    $ref: 'requests/jetdrops-byjetid.yaml'
  /api/v1/jetdrops/{jet_drop_id}/records:
    $ref: 'requests/records.yaml'
  /api/v1/lifeline/{object_reference}/records:
    $ref: 'requests/lifeline.yaml'
  /api/v1/search:
    $ref: 'requests/search.yaml'

